version: 0.2

phases:
    install:
        runtime-versions:
               nodejs: 10
               commands:
                  - echo "Installing something"
  pre_build:
    commands:
       - echo "we are in the per build phase"
  build:
    commands:
      - echo "we are in the build phase"
      - echo "we are in run some tests"
  post_build:
    commands:
      - echo "we are in the post_build phase"
